### ISSUE TITLE
Where is computer exactly?

### ISSUE THREAD

**Issue by MidOutGaming** [Summerxo/esx_computer#1]
I'm not sure I understood this script right, can't find PC, that needs to be used to hack. Or do I need to do "computer" item and put it into the shop?

**Comment by Summerxo** [comment]
No computer in the shop. To hack, you have to have a job set as hacker (DB SQL insert) and it is the model of the PC which you can find in various parts of the map. Mission Row, Life-invader have the computer model there. To change the model you just have to get the Prop ID for it if you don't like the current model being used. 

![20190501144145_1](https://user-images.githubusercontent.com/24981472/59946183-704d5200-942f-11e9-8e39-60eddffe9719.jpg)

**Comment by MidOutGaming** [comment]
Oh cool, thanks :)
